name: Firebase Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install --prefix=./backend/sendmessage/functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        working-directory: ./backend/sendmessage
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: bigchat-88c14
